site_name: IPFabric
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

extra:
  version:
    provider: mike

plugins:
  - search:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
